src/YounicornApp.Web/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YounicornApp.Core.Interfaces;
using YounicornApp.Web.ApiModels;

namespace YounicornApp.Web.Controllers
{
    public class DashboardController : Controller
    {
        private readonly IAnalyticsService _analyticsService;
        public DashboardController(IAnalyticsService analyticsService)
        {
            _analyticsService = analyticsService;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> GetAnalyticValues(AnalyticsRequestDTO request) 
        {
            var result = await _analyticsService.GetAnalytics(request: request.ToRequest());
            return Json(result);
        }
    }
}

src/YounicornApp.Web/Controllers/EmailTemplateController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YounicornApp.Core.Interfaces;
using YounicornApp.Web.ApiModels;

namespace YounicornApp.Web.Controllers
{
    public class EmailTemplateController : Controller
    {
        private readonly IEmailSender EmailSender;
        private readonly IEmailService EmailService;

        public EmailTemplateController(IEmailSender _emailSender, IEmailService _emailService)
        {
            EmailSender = _emailSender;
            EmailService = _emailService;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetEmailAsync(string type)
        {
            try
            {
                int id = string.IsNullOrEmpty(type) ? 1 : type.Equals("NewSignup") ? 1 : 2;
                var result = await EmailService.GetEmailTemplateById(id);
                return Json(result);
            }
            catch (Exception exp)
            {
                return Json(string.Empty);
            }
            
        }


        [HttpPost]
        public async Task<IActionResult> TestEmailAsync(EmailTemplateDTO model)
        {
            if (model.isValid())
            {
                var item = await EmailService.TestEmailAsync(new Core.Entities.EmailTemplate
                {
                    Body = model.Body,
                    Subject = model.Subject,
                    SendBCC = model.SendBCC,
                    SendCC = model.SendCC
                }, model.Type);

                return Json(new EmailResponse { Message = item.Message, Success = item.Success });
            }
            else
            {
                return Json(new EmailResponse { Message = "Model is Invalid", Success = false });
            }
        }

        [HttpPost]
        public IActionResult SaveEmail(EmailTemplateDTO model)
        {
            if (model.isValid())
            {
                var emailTemplate = EmailService.UpdateEmailTemplate(
                    new Core.Entities.EmailTemplate 
                    {
                        Id = model.Type.Equals("NewSignup") ? 1 : 2,
                        Body = model.Body,
                        Subject = model.Subject,
                        SendBCC = model.SendBCC,
                        SendCC = model.SendCC
                    }
                    );
                return Json(new EmailResponse { Message = "Email Is Updated.", Success = false });
            }
            else
            {
                return Json(new EmailResponse { Message = "Model is Invalid", Success = false });
            }
        }
    }
}

src/YounicornApp.Web/Controllers/ProviderController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using YounicornApp.Core.Entities;
using YounicornApp.Core.Interfaces;
using YounicornApp.SharedKernel.Interfaces;
using YounicornApp.Web.ApiModels;

namespace YounicornApp.Web.Controllers
{
    public class ProviderController : Controller
    {
        private readonly IProviderService _service;
        private readonly ILogger<ProviderController> _logger;

        public ProviderController(IProviderService service, ILogger<ProviderController> logger)
        {
            _service = service;
            _logger = logger;
        }

        // GET: ProviderController
        public ActionResult Index()
        {           
            return View();
        }

        public async Task<IActionResult> GetProviders()
        {
            var items = (await _service.GetItemsAsync())
                              .Select(ProviderItemDTO.FromProviderItem)
                              .ToList();
            return Json(new { data = items });
        }

        [HttpGet]
        public async Task<IActionResult> Save(int id)
        {
            if(id <= 0) return View();
           
            return View(ProviderItemDTO.FromProviderItem(await _service.GetProviderById(id)));
        }

        [HttpPost]
        public async Task<JsonResult> Save(ProviderItemDTO providerDto)
        {
            if (ModelState.IsValid)
            {
                var provider = ProviderItemDTO.ToProviderItem(providerDto);
                provider.LogoUrl = providerDto.LogoFile != null ? UploadFile(providerDto.LogoFile) : providerDto.LogoUrl;

                if (provider.Id > 0)
                {
                    await _service.UpdateProvider(provider);
                }
                else
                {
                    await _service.CreateProvider(provider);  
                }

                return Json(new { status = true });                
            }
            return Json(null);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) return View();

            return View(ProviderItemDTO.FromProviderItem(await _service.GetProviderById(id)));
        }

        // POST: ProviderController/Delete/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<JsonResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                await _service.DeleteProviderAsync(id);
                return Json(new { status = true });
            }
            catch
            {
                return Json(new { status = false });
            }
        }

        [HttpPost]
        public string UploadFile(IFormFile file)
        {
            if (file == null || file.Length == 0)
                return string.Empty;

            var path = Path.Combine(
                        Directory.GetCurrentDirectory(), "wwwroot\\img\\provider",
                        Path.GetFileName(file.FileName));

            using (var stream = new FileStream(path, FileMode.Create))
            {
                file.CopyToAsync(stream);
            }

            return file.FileName;
        }
    }
}

src/YounicornApp.Web/Controllers/UserActionsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YounicornApp.Core.Interfaces;
using YounicornApp.Web.ApiModels;

namespace YounicornApp.Web.Controllers
{
    public class UserActionsController : Controller
    {
        private readonly IUserHistoryService _userHistoryService;
        public UserActionsController(IUserHistoryService userHistoryService)
        {
            _userHistoryService = userHistoryService;
        }
        public IActionResult Index()
        {
            return View();
        }
        
        [HttpGet]
        public async Task<IActionResult> GetUserActions() 
        {
            try
            {
                var result = await _userHistoryService.GetUserHistories();
                var userHistories = result.userHistories;
                var ispDetail = result.ispDetail;
                var ispOffers = result.ispOffers;
                var data = from hist in userHistories
                           join ispD in ispDetail on hist.IspId equals ispD.Id
                           join ispO in ispOffers on hist.IspOfferId equals ispO.Id
                           select new UserActionDTO
                           { 
                               ActionId = hist.Id,
                               IspId = hist.IspId,
                               IspOfferId = hist.IspOfferId,
                               UserAddress = hist.UserAddress,
                               EnquiryId = hist.EnquiryId,
                               ActionType = hist.ActionType,
                               ActionDetails = hist.ActionDetails,
                               ActionDatetime = hist.ActionDatetime,
                               ISPDetail = ispD.Displayname,
                               ISPOfferDetail = ispO.Displayname,
                               SessionId = hist.SessionId
                           };
                return Json(new { data = data.ToList() });
            }
            catch (Exception exp)
            {
                return Json(exp.Message);
            }
        }

        [HttpGet]
        public async Task<IActionResult> UserActionDetail(int id)
        {
            if (id <= 0) return View();
            var result = await _userHistoryService.GetUserHistory(id);
            string ispDisplayName = (await _userHistoryService.GetISP(int.Parse(result.IspId.Value.ToString()))).Value;
            string ispOfferName = (await _userHistoryService.GetISPOffers(int.Parse(result.IspOfferId.Value.ToString()))).Value;
            return View(UserActionDTO.FromUserHistory(result, ispDisplayName, ispOfferName));
        }

        [HttpGet]
        public async Task<IActionResult> GetISPAsync()
        {
            try
            {
                var result = await _userHistoryService.GetISP();
                return Json(result);
            }
            catch (Exception exp)
            {
                return Json(exp.Message);
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetActionType()
        {
            try
            {
                var result = await _userHistoryService.GetActionType();
                return Json(result);
            }
            catch (Exception exp)
            {
                return Json(exp.Message);
            }
        }

        [HttpGet]
        public async Task<IActionResult> GetISPOfferAsync()
        {
            try
            {
                var result = await _userHistoryService.GetISPOffers();
                return Json(result);
            }
            catch (Exception exp)
            {
                return Json(exp.Message);
            }
        }
    }
}

src/YounicornApp.Web/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Younicorn</title>
    @*Google Fonts*@
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <environment names="Development">
        <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
        <link href="~/lib/Others/icofont/icofont.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
        <link href="~/lib/font-awesome/css/fontawesome.min.css" rel="stylesheet" />
        <link href="~/lib/animate.css/animate.min.css" rel="stylesheet" />
        <link href="~/lib/OwlCarousel2/assets/owl.carousel.min.css" rel="stylesheet" />
        <link href="~/lib/aos/aos.css" rel="stylesheet" />
        <link href="~/img/favicon.png" rel="icon">
        <link href="~/lib/jquery.datatable/css/jquery.dataTables.min.css" rel="stylesheet" />
        <link href="~/lib/jqueryui/jquery-ui.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.css" rel="stylesheet" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/4.6.0/css/bootstrap.min.css"
              asp-fallback-href="~/lib/twitter-bootstrap/css/bootstrap.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link href="~/lib/Others/icofont/icofont.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
              asp-fallback-href="~/lib/font-awesome/css/all.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/fontawesome.min.css"
              asp-fallback-href="~/lib/font-awesome/css/fontawesome.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
              asp-fallback-href="~/lib/animate.css/animate.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
              asp-fallback-href="~/lib/OwlCarousel2/assets/owl.carousel.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/aos/2.3.4/aos.css"
              asp-fallback-href="~/lib/aos/aos.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/css/jquery.dataTables.min.css"
              asp-fallback-href="~/lib/jquery.datatable/css/jquery.dataTables.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css"
              asp-fallback-href="~/lib/jqueryui/jquery-ui.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @*Template Main CSS File*@

    @*<link href="~/css/responsive.css" rel="stylesheet">*@
    <link href="~/css/style.css" rel="stylesheet">
</head>
<body>
    <header id="header" class="">
        <div class="container">
            <div class="row align-items-center">
                <!-- Uncomment below if you prefer to use an text logo -->
                <!--<h1 class="logo mr-auto"><a href="index.html">Restaurantly</a></h1>-->
                <!-- Uncomment below if you prefer to use an image logo -->
                <div class="col-auto">
                    <a href="@Url.ActionLink("Index","Dashboard")" class="logo mr-auto"><img src="@Url.Content("~/img/logo.png")" alt="" class="img-fluid"></a>
                </div>

                <div class="col">
                    <div class="d-flex justify-content-end align-items-center align-items-md-start">
                        <nav class="nav-menu d-none d-md-block py-3">
                            <ul>
                                <li><a href="@Url.ActionLink("index","Provider")">Provider Info</a></li>
                                <li><a href="@Url.ActionLink("index","EmailTemplate")">Email Template</a></li>
                                <li><a href="@Url.ActionLink("index","UserActions")">User Actions</a></li>
                            </ul>
                        </nav><!-- .nav-menu -->
                        <!-- .navbar-nav-right -->
                        <ul class="navbar-nav-right d-none d-md-flex align-items-center pt-2 pb-3 px-3 mb-4">
                            <li>
                                <a href="#">
                                    Got a question?<br>
                                    Talk to Younicorn staff now.
                                </a>
                            </li>
                            <li>
                                <a href="#menu"><i class="material-icons">chat</i>&nbsp;Chat</a>
                            </li>
                            <li>
                                <a href="#menu"><i class="material-icons">call</i>&nbsp;Call</a>
                            </li>
                        </ul>
                        <!-- .navbar--nav-right -->
                        <div class="logo-right d-none d-lg-block  pt-2 pb-3">
                            <a href="@Url.ActionLink("login","home")" onclick="window.localStorage.setItem('userid', '');"><img src="@Url.Content("~/img/favicon.png")" alt="" class="img-fluid"></a>
                        </div>
                        <div class="d-md-none">
                            <button type="button" class="mobile-nav-toggle d-lg-none"><i class="icofont-navigation-menu"></i></button>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </header><!-- End Header -->
    <div class="box-body">
        <div class="borderbox">
            @RenderBody()
        </div>
        <!-- End Footer -->

        <div id="preloader"></div>
        <a href="#" class="back-to-top"><i class="fa fa-arrow-up"></i></a>
    </div>

    <environment names="Development">
        <script src="@Url.Content("~/lib/jquery/jquery.js")"></script>
        <script src="@Url.Content("~/lib/twitter-bootstrap/js/bootstrap.js")"></script>
        <script src="@Url.Content("~/lib/jqueryui/jquery-ui.js")"></script>
        <script src="@Url.Content("~/lib/jquery.datatable/js/jquery.dataTables.min.js")"></script>
        <script src="@Url.Content("~/js/site.js")" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"
                asp-fallback-src="~/lib/jquery/jquery.min.js"
                asp-fallback-test="window.jQuery"></script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/twitter-bootstrap/js/bootstrap.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
                asp-fallback-src="~/lib/jqueryui/jquery-ui.min.js"
                asp-fallback-test="window.jQueryui"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.21/js/jquery.dataTables.min.js"
                asp-fallback-src="~/lib/jquery.datatable/js/jquery.dataTables.min.js"
                asp-fallback-test="window.jQueryDataTables"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @*Template Main JS File*@
    <script src="@Url.Content("~/vendor/jquery.easing/jquery.easing.min.js")"></script>
    <script src="@Url.Content("~/vendor/owl.carousel/owl.carousel.min.js")"></script>
    <script src="@Url.Content("~/vendor/aos/aos.js")"></script>
    <script src="@Url.Content("~/js/main.js")"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-toast-plugin/1.3.2/jquery.toast.min.js"></script>
    <script src="~/js/moment.js"></script>
    @await RenderSectionAsync("scripts", required: false).ConfigureAwait(false)
</body>
</html>