src/YounicornApp.Web/Controllers/IspOfferController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using YounicornApp.Core.Entities;
using YounicornApp.Core.Interfaces;
using YounicornApp.Web.ApiModels;

namespace YounicornApp.Web.Controllers
{
    public class IspOfferController : Controller
    {
        private readonly IIspOfferService _service;
        private readonly ILogger<IspOfferController> _logger;

        public IspOfferController(IIspOfferService service, ILogger<IspOfferController> logger)
        {
            _service = service;
            _logger = logger;
        }

        // GET: IspOfferController
        public ActionResult Index(int id)
        {
            ViewBag.ProviderId = id;            
            return View();
        }


        public async Task<IActionResult> GetOffers(int providerId)
        {
            var items = (await _service.GetItemsByProviderIdAsync(providerId))
                              .Select(IspOfferItemDTO.FromIspOfferItem)
                              .ToList();
            return Json(new { data = items });
        }

        public async Task<IActionResult> GetAllOffers()
        {
            var items = (await _service.GetItemsAsync())
                              .Select(IspOfferItemDTO.FromIspOfferItem)
                              .ToList();
            return Json(new { data = items });
        }

        [HttpGet]
        public async Task<IActionResult> Save(int id, int pId)
        {
            if (id <= 0) return View(new IspOfferItemDTO { Ispid = pId });

            return View(IspOfferItemDTO.FromIspOfferItem(await _service.GetOfferById(id)));
        }

        [HttpPost]
        public async Task<JsonResult> Save(IspOffer offer)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (offer.Id > 0)
                    {
                        await _service.UpdateOffer(offer);
                    }
                    else
                    {
                        await _service.CreateOffer(offer);
                    }

                    return Json(new { status = true });
                }
            }
            catch (Exception ex)
            {
                return Json(new { Error = ex.Message });
            }
           
            return Json(null);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) return View();

            return View(IspOfferItemDTO.FromIspOfferItem(await _service.GetOfferById(id)));
        }

        // POST: ProviderController/Delete/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<JsonResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                await _service.DeleteOfferAsync(id);
                return Json(new { status = true });
            }
            catch
            {
                return Json(new { status = false });
            }
        }
    }
}

src/YounicornApp.Web/Views/IspOffer/Delete.cshtml
@model YounicornApp.Web.ApiModels.IspOfferItemDTO
@{ Layout = ""; }

@using (Html.BeginForm("Delete", "IspOffer", FormMethod.Post, new { id = "popupForm" }))
{
@Html.HiddenFor(a => a.Id)

                <div class="container">
                    <div class="row">
                        <div class="col-md-10 mx-auto">
                            <form>
                                <div class="form-group row">
                                    <div class="col-sm-6">
                                        <label>Isp Id</label>
                                        <p>@Model.Ispid</p>
                                    </div>
                                    @if (Model != null && Model.Id > 0)
                                    {
                    <div class="col-sm-6">
                        <label>Offer Id</label>
                        <p>@Model.Id</p>
                    </div>}
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6">
                                        <label>Offer Name</label>
                                        <p>@Model.Offername</p>
                                    </div>
                                    <div class="col-sm-6">
                                        <label>Display Name</label>
                                        <p>@Model.Displayname</p>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6">
                                        <label>Speed</label>
                                        <p>@Model.Speed</p>
                                    </div>
                                    <div class="col-sm-6">
                                        <label>Data</label>
                                        <p>@Model.Data</p>
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-sm-6">
                                        <label>Price month</label>
                                        <p>@Model.Pricemonth</p>
                                    </div>
                                    <div class="col-sm-6">
                                        <label>Price annual</label>
                                        <p>@Model.Priceannual</p>
                                    </div>
                                </div>

                                <div class="d-flex justify-content-center">
                                    <button type="submit" value="Delete" class="btn btn-primary px-4 float-right btn-dark-tangerine btn-rounded">Delete</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>}

src/YounicornApp.Web/Views/IspOffer/Index.cshtml
@model IEnumerable<YounicornApp.Web.ApiModels.IspOfferItemDTO>

@{ ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml"; }
<style>

    .ui-dialog .ui-dialog-titlebar {
        padding: 10px;
        position: relative;
    }

    table.dataTable tbody th, table.dataTable tbody td {
        padding: 8px 21px;
    }
</style>
<nav class="breadcrumb">
    <div class="container">
        <a class="breadcrumb-item" href="/">Home</a>
        <a class="breadcrumb-item" href="/Provider/">Provider</a>
        <a class="breadcrumb-item active">ISP Offer</a>
    </div>
</nav>
<div style="width:90%; margin:0 auto" class="tablecontainer">

    <input type="hidden" id="hidProviderId" value="@ViewBag.ProviderId" />
    <div class="heading-title">
        <h2>
            ISP Offers
        </h2>
    </div>
    <a class="popup btn btn-primary btn-dark-tangerine btn-rounded" href="/IspOffer/Save/0?pId=@ViewBag.ProviderId" style="margin-bottom:20px; margin-top:20px;float:right">Add New Offer</a>
    <table id="myDatatable">
        <thead>
            <tr>
                <th>
                    Offer ID
                </th>
                <th>
                    Name
                </th>
                <th>
                    Display
                </th>
                <th>
                    Speed
                </th>
                <th>
                    Data
                </th>
                <th>
                    $Month
                </th>
                <th>
                    $Annual
                </th>
                <th>Action</th>

            </tr>
        </thead>
    </table>
</div>

@section Scripts {
    <script src="~/js/offers.js" asp-append-version="true"></script>
}

src/YounicornApp.Web/Views/IspOffer/Save.cshtml
@model YounicornApp.Web.ApiModels.IspOfferItemDTO
@{ Layout = ""; }


@using (Html.BeginForm("Save", "IspOffer", FormMethod.Post, new { id = "popupForm" }))
{
    if (Model != null && Model.Id > 0)
    {@Html.HiddenFor(a => a.Id) }

<div class="container">
    <div class="row">
        <div class="col-md-12 mx-auto textbox">
            <form>
                <div class="form-group row">
                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Offer ID</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Ispid, new { @class = "form-control numerictext", @readonly = "readonly" })
                        </div>
                    </div>

                    @if (Model != null && Model.Id > 0)
                    {
    <div class="col-sm-6 row">
        <div class="col-sm-4">
            <label>Offer Id</label>
        </div>
        <div class="col-sm-8">
            @Html.TextBoxFor(a => a.Id, new { @class = "form-control numerictext", @readonly = "readonly" })
        </div>
    </div>}

                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Offer Name</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Offername, new { @class = "form-control" })
                            @Html.ValidationMessageFor(a => a.Offername)
                        </div>
                    </div>
                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Display Name</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Displayname, new { @class = "form-control" })
                            @Html.ValidationMessageFor(a => a.Displayname)
                        </div>
                    </div>

                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Speed</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Speed, new { @class = "form-control numerictext" })
                            @Html.ValidationMessageFor(a => a.Speed)
                        </div>
                    </div>
                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Data</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Data, new { @class = "form-control numerictext" })
                            @Html.ValidationMessageFor(a => a.Data)
                        </div>
                    </div>

                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Price month</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Pricemonth, new { @class = "form-control numerictext" })
                            @Html.ValidationMessageFor(a => a.Pricemonth)
                        </div>
                    </div>
                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Price annual</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Priceannual, new { @class = "form-control numerictext" })
                            @Html.ValidationMessageFor(a => a.Priceannual)
                        </div>
                    </div>

                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Bundle details</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Bundledetails, new { @class = "form-control" })
                            @Html.ValidationMessageFor(a => a.Bundledetails)
                        </div>
                    </div>
                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Bullet 1</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Bullet1, new { @class = "form-control" })
                            @Html.ValidationMessageFor(a => a.Bullet1)
                        </div>
                    </div>

                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Bullet 2</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Bullet2, new { @class = "form-control" })
                            @Html.ValidationMessageFor(a => a.Bullet2)
                        </div>
                    </div>
                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Bullet 3</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Bullet3, new { @class = "form-control" })
                            @Html.ValidationMessageFor(a => a.Bullet3)
                        </div>
                    </div>

                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Bullet 4</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Bullet4, new { @class = "form-control" })
                            @Html.ValidationMessageFor(a => a.Bullet4)
                        </div>
                    </div>
                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Bullet 5</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Bullet5, new { @class = "form-control" })
                            @Html.ValidationMessageFor(a => a.Bullet5)
                        </div>
                    </div>

                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Discount details</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Discountdetails, new { @class = "form-control" })
                            @Html.ValidationMessageFor(a => a.Discountdetails)
                        </div>
                    </div>
                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Installation cost</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Installationcost, new { @class = "form-control numerictext" })
                            @Html.ValidationMessageFor(a => a.Installationcost)
                        </div>
                    </div>

                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Modem cost</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Modemcost, new { @class = "form-control numerictext" })
                            @Html.ValidationMessageFor(a => a.Modemcost)
                        </div>
                    </div>
                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Termination fee</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Terminationfee, new { @class = "form-control numerictext" })
                            @Html.ValidationMessageFor(a => a.Terminationfee)
                        </div>
                    </div>

                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Favourite</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Favourite, new { @class = "form-control numerictext" })
                            @Html.ValidationMessageFor(a => a.Favourite)
                        </div>
                    </div>
                    <div class="col-sm-6 row">
                        <div class="col-sm-4">
                            <label>Offer Rating</label>
                        </div>
                        <div class="col-sm-8">
                            @Html.TextBoxFor(a => a.Offerrating, new { @class = "form-control numerictext" })
                            @Html.ValidationMessageFor(a => a.Offerrating)
                        </div>
                    </div>
                </div>
                <div class="form-group row checkboxlist text-center">
                    <div class="col-sm-1">
                        <label for="Adsl">ADSL</label>
                        @Html.CheckBoxFor(a => a.Adsl, new { @class = "form-control" })
                        @Html.ValidationMessageFor(a => a.Offerrating)
                    </div>
                    <div class="col-sm-1">
                        <label for="Vdsl">VDSL</label>
                        @Html.CheckBoxFor(a => a.Vdsl, new { @class = "form-control" })
                        @Html.ValidationMessageFor(a => a.Offerrating)
                    </div>
                    <div class="col-sm-1">
                        <label for="Fibre">Fibre</label>
                        @Html.CheckBoxFor(a => a.Fibre, new { @class = "form-control" })
                        @Html.ValidationMessageFor(a => a.Fibre)
                    </div>
                    <div class="col-sm-1">
                        <label for="Fibreplus">Fibreplus</label>
                        @Html.CheckBoxFor(a => a.Fibreplus, new { @class = "form-control" })
                        @Html.ValidationMessageFor(a => a.Fibreplus)
                    </div>
                </div>

                <div class="d-flex justify-content-center">
                    <button type="submit" value="Save" class="mt-18 btn btn-primary float-right btn-dark-tangerine btn-rounded text-uppercase font-weight-bold w-50">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>}